
matrix:
 include:
language: node_js
node_js:
  - "stable"
before_script:
  - cd client
script:
  - npm install
  
language: java
sudo: false
addons:
sonarcloud:
organization: "educadia-github"
token:
secure: 47505f2e1e8debe319a3369d20f57811ef9b9414
jdk:
-oraclejdk8
script:

cache:
 directories:
 -'$HOME/.m2/repository'
 -'$HOME/.sonar/cache'
